package com.thermondo.database

import com.thermondo.database.model.launch.*

val fakeInMemoryLaunches = listOf(
    LaunchEntity(
        id = "1",
        autoUpdate = false,
        capsules = listOf(),
        cores = listOf(),
        crew = listOf(),
        dateLocal = "sonet",
        datePrecision = "dicat",
        dateUnix = 6976,
        dateUtc = "at",
        details = null,
        failures = listOf(),
        fairings = null,
        flightNumber = 8999,
        launchLibraryId = null,
        launchpad = "cras",
        links = LinksEntity(
            article = null,
            flickr = FlickrEntity(
                original = listOf(),
                small = listOf()
            ),
            patch = PatchEntity(large = null, small = null),
            presskit = null,
            reddit = RedditEntity(
                campaign = null,
                launch = null,
                media = null,
                recovery = null
            ),
            webcast = null,
            wikipedia = null,
            youtubeId = null
        ),
        name = "Willa Vang",
        net = false,
        payloads = listOf(),
        rocket = "odio",
        ships = listOf(),
        staticFireDateUnix = null,
        staticFireDateUtc = null,
        success = null,
        tbd = false,
        upcoming = false,
        window = null
    ),
    LaunchEntity(
        id = "2",
        autoUpdate = false,
        capsules = listOf(),
        cores = listOf(),
        crew = listOf(),
        dateLocal = "sonet",
        datePrecision = "dicat",
        dateUnix = 6976,
        dateUtc = "at",
        details = null,
        failures = listOf(),
        fairings = null,
        flightNumber = 8999,
        launchLibraryId = null,
        launchpad = "cras",
        links = LinksEntity(
            article = null,
            flickr = FlickrEntity(
                original = listOf(),
                small = listOf()
            ),
            patch = PatchEntity(large = null, small = null),
            presskit = null,
            reddit = RedditEntity(
                campaign = null,
                launch = null,
                media = null,
                recovery = null
            ),
            webcast = null,
            wikipedia = null,
            youtubeId = null
        ),
        name = "Willa Vang",
        net = false,
        payloads = listOf(),
        rocket = "odio",
        ships = listOf(),
        staticFireDateUnix = null,
        staticFireDateUtc = null,
        success = null,
        tbd = false,
        upcoming = false,
        window = null
    ),
    LaunchEntity(
        id = "3",
        autoUpdate = false,
        capsules = listOf(),
        cores = listOf(),
        crew = listOf(),
        dateLocal = "sonet",
        datePrecision = "dicat",
        dateUnix = 6976,
        dateUtc = "at",
        details = null,
        failures = listOf(),
        fairings = null,
        flightNumber = 8999,
        launchLibraryId = null,
        launchpad = "cras",
        links = LinksEntity(
            article = null,
            flickr = FlickrEntity(
                original = listOf(),
                small = listOf()
            ),
            patch = PatchEntity(large = null, small = null),
            presskit = null,
            reddit = RedditEntity(
                campaign = null,
                launch = null,
                media = null,
                recovery = null
            ),
            webcast = null,
            wikipedia = null,
            youtubeId = null
        ),
        name = "Willa Vang",
        net = false,
        payloads = listOf(),
        rocket = "odio",
        ships = listOf(),
        staticFireDateUnix = null,
        staticFireDateUtc = null,
        success = null,
        tbd = false,
        upcoming = false,
        window = null
    ),
    LaunchEntity(
        id = "4",
        autoUpdate = false,
        capsules = listOf(),
        cores = listOf(),
        crew = listOf(),
        dateLocal = "sonet",
        datePrecision = "dicat",
        dateUnix = 6976,
        dateUtc = "at",
        details = null,
        failures = listOf(),
        fairings = null,
        flightNumber = 8999,
        launchLibraryId = null,
        launchpad = "cras",
        links = LinksEntity(
            article = null,
            flickr = FlickrEntity(
                original = listOf(),
                small = listOf()
            ),
            patch = PatchEntity(large = null, small = null),
            presskit = null,
            reddit = RedditEntity(
                campaign = null,
                launch = null,
                media = null,
                recovery = null
            ),
            webcast = null,
            wikipedia = null,
            youtubeId = null
        ),
        name = "Willa Vang",
        net = false,
        payloads = listOf(),
        rocket = "odio",
        ships = listOf(),
        staticFireDateUnix = null,
        staticFireDateUtc = null,
        success = null,
        tbd = false,
        upcoming = false,
        window = null
    ),
    LaunchEntity(
        id = "5",
        autoUpdate = false,
        capsules = listOf(),
        cores = listOf(),
        crew = listOf(),
        dateLocal = "sonet",
        datePrecision = "dicat",
        dateUnix = 6976,
        dateUtc = "at",
        details = null,
        failures = listOf(),
        fairings = null,
        flightNumber = 8999,
        launchLibraryId = null,
        launchpad = "cras",
        links = LinksEntity(
            article = null,
            flickr = FlickrEntity(
                original = listOf(),
                small = listOf()
            ),
            patch = PatchEntity(large = null, small = null),
            presskit = null,
            reddit = RedditEntity(
                campaign = null,
                launch = null,
                media = null,
                recovery = null
            ),
            webcast = null,
            wikipedia = null,
            youtubeId = null
        ),
        name = "Willa Vang",
        net = false,
        payloads = listOf(),
        rocket = "odio",
        ships = listOf(),
        staticFireDateUnix = null,
        staticFireDateUtc = null,
        success = null,
        tbd = false,
        upcoming = false,
        window = null
    ),
    LaunchEntity(
        id = "6",
        autoUpdate = false,
        capsules = listOf(),
        cores = listOf(),
        crew = listOf(),
        dateLocal = "sonet",
        datePrecision = "dicat",
        dateUnix = 6976,
        dateUtc = "at",
        details = null,
        failures = listOf(),
        fairings = null,
        flightNumber = 8999,
        launchLibraryId = null,
        launchpad = "cras",
        links = LinksEntity(
            article = null,
            flickr = FlickrEntity(
                original = listOf(),
                small = listOf()
            ),
            patch = PatchEntity(large = null, small = null),
            presskit = null,
            reddit = RedditEntity(
                campaign = null,
                launch = null,
                media = null,
                recovery = null
            ),
            webcast = null,
            wikipedia = null,
            youtubeId = null
        ),
        name = "Willa Vang",
        net = false,
        payloads = listOf(),
        rocket = "odio",
        ships = listOf(),
        staticFireDateUnix = null,
        staticFireDateUtc = null,
        success = null,
        tbd = false,
        upcoming = false,
        window = null
    ),
    LaunchEntity(
        id = "7",
        autoUpdate = false,
        capsules = listOf(),
        cores = listOf(),
        crew = listOf(),
        dateLocal = "sonet",
        datePrecision = "dicat",
        dateUnix = 6976,
        dateUtc = "at",
        details = null,
        failures = listOf(),
        fairings = null,
        flightNumber = 8999,
        launchLibraryId = null,
        launchpad = "cras",
        links = LinksEntity(
            article = null,
            flickr = FlickrEntity(
                original = listOf(),
                small = listOf()
            ),
            patch = PatchEntity(large = null, small = null),
            presskit = null,
            reddit = RedditEntity(
                campaign = null,
                launch = null,
                media = null,
                recovery = null
            ),
            webcast = null,
            wikipedia = null,
            youtubeId = null
        ),
        name = "Willa Vang",
        net = false,
        payloads = listOf(),
        rocket = "odio",
        ships = listOf(),
        staticFireDateUnix = null,
        staticFireDateUtc = null,
        success = null,
        tbd = false,
        upcoming = false,
        window = null
    ),
    LaunchEntity(
        id = "8",
        autoUpdate = false,
        capsules = listOf(),
        cores = listOf(),
        crew = listOf(),
        dateLocal = "sonet",
        datePrecision = "dicat",
        dateUnix = 6976,
        dateUtc = "at",
        details = null,
        failures = listOf(),
        fairings = null,
        flightNumber = 8999,
        launchLibraryId = null,
        launchpad = "cras",
        links = LinksEntity(
            article = null,
            flickr = FlickrEntity(
                original = listOf(),
                small = listOf()
            ),
            patch = PatchEntity(large = null, small = null),
            presskit = null,
            reddit = RedditEntity(
                campaign = null,
                launch = null,
                media = null,
                recovery = null
            ),
            webcast = null,
            wikipedia = null,
            youtubeId = null
        ),
        name = "Willa Vang",
        net = false,
        payloads = listOf(),
        rocket = "odio",
        ships = listOf(),
        staticFireDateUnix = null,
        staticFireDateUtc = null,
        success = null,
        tbd = false,
        upcoming = false,
        window = null
    )
)